# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../qt-proj/space-app-challenge/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(771, 603)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 751, 161))
        self.groupBox.setObjectName("groupBox")
        self.chb_raw = QtWidgets.QCheckBox(self.groupBox)
        self.chb_raw.setGeometry(QtCore.QRect(180, 49, 86, 21))
        self.chb_raw.setChecked(True)
        self.chb_raw.setObjectName("chb_raw")
        self.lbl_download = QtWidgets.QLabel(self.groupBox)
        self.lbl_download.setGeometry(QtCore.QRect(690, 120, 51, 21))
        self.lbl_download.setObjectName("lbl_download")
        self.cb_doy = QtWidgets.QComboBox(self.groupBox)
        self.cb_doy.setGeometry(QtCore.QRect(480, 48, 81, 26))
        self.cb_doy.setCurrentText("")
        self.cb_doy.setObjectName("cb_doy")
        self.pb_download = QtWidgets.QPushButton(self.groupBox)
        self.pb_download.setGeometry(QtCore.QRect(610, 46, 131, 32))
        self.pb_download.setObjectName("pb_download")
        self.pb_change_download_addr = QtWidgets.QPushButton(self.groupBox)
        self.pb_change_download_addr.setGeometry(QtCore.QRect(690, 77, 51, 32))
        self.pb_change_download_addr.setObjectName("pb_change_download_addr")
        self.pbar_download = QtWidgets.QProgressBar(self.groupBox)
        self.pbar_download.setGeometry(QtCore.QRect(20, 120, 661, 23))
        self.pbar_download.setMinimum(0)
        self.pbar_download.setProperty("value", 0)
        self.pbar_download.setObjectName("pbar_download")
        self.cb_year = QtWidgets.QComboBox(self.groupBox)
        self.cb_year.setGeometry(QtCore.QRect(320, 48, 91, 26))
        self.cb_year.setObjectName("cb_year")
        self.txt_download_addr = QtWidgets.QLineEdit(self.groupBox)
        self.txt_download_addr.setGeometry(QtCore.QRect(120, 80, 561, 21))
        self.txt_download_addr.setObjectName("txt_download_addr")
        self.lbl_year = QtWidgets.QLabel(self.groupBox)
        self.lbl_year.setGeometry(QtCore.QRect(280, 51, 62, 17))
        self.lbl_year.setObjectName("lbl_year")
        self.lbl_doy = QtWidgets.QLabel(self.groupBox)
        self.lbl_doy.setGeometry(QtCore.QRect(440, 51, 62, 17))
        self.lbl_doy.setObjectName("lbl_doy")
        self.rb_ftp = QtWidgets.QRadioButton(self.groupBox)
        self.rb_ftp.setGeometry(QtCore.QRect(15, 30, 102, 21))
        self.rb_ftp.setObjectName("rb_ftp")
        self.rb_doy = QtWidgets.QRadioButton(self.groupBox)
        self.rb_doy.setGeometry(QtCore.QRect(15, 55, 102, 21))
        self.rb_doy.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.rb_doy.setChecked(True)
        self.rb_doy.setObjectName("rb_doy")
        self.rb_local = QtWidgets.QRadioButton(self.groupBox)
        self.rb_local.setGeometry(QtCore.QRect(15, 80, 102, 21))
        self.rb_local.setObjectName("rb_local")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 751, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lbl_cleaning = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_cleaning.setGeometry(QtCore.QRect(690, 40, 51, 21))
        self.lbl_cleaning.setObjectName("lbl_cleaning")
        self.pbar_cleaning = QtWidgets.QProgressBar(self.groupBox_2)
        self.pbar_cleaning.setGeometry(QtCore.QRect(20, 40, 661, 23))
        self.pbar_cleaning.setMinimum(0)
        self.pbar_cleaning.setProperty("value", 0)
        self.pbar_cleaning.setObjectName("pbar_cleaning")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 751, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lbl_cleaned_addr = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_cleaned_addr.setGeometry(QtCore.QRect(20, 30, 721, 20))
        self.lbl_cleaned_addr.setText("")
        self.lbl_cleaned_addr.setObjectName("lbl_cleaned_addr")
        self.pb_load_cleaned = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_load_cleaned.setGeometry(QtCore.QRect(520, 30, 211, 32))
        self.pb_load_cleaned.setObjectName("pb_load_cleaned")
        self.lbl_orbit = QtWidgets.QLabel(self.groupBox_3)
        self.lbl_orbit.setGeometry(QtCore.QRect(690, 40, 51, 21))
        self.lbl_orbit.setObjectName("lbl_orbit")
        self.pbar_orbit = QtWidgets.QProgressBar(self.groupBox_3)
        self.pbar_orbit.setGeometry(QtCore.QRect(20, 40, 661, 23))
        self.pbar_orbit.setMinimum(0)
        self.pbar_orbit.setProperty("value", 0)
        self.pbar_orbit.setObjectName("pbar_orbit")
        self.tb_orbits = QtWidgets.QTableWidget(self.groupBox_3)
        self.tb_orbits.setEnabled(True)
        self.tb_orbits.setGeometry(QtCore.QRect(30, 80, 539, 51))
        self.tb_orbits.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tb_orbits.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tb_orbits.setAutoScroll(False)
        self.tb_orbits.setRowCount(2)
        self.tb_orbits.setColumnCount(6)
        self.tb_orbits.setObjectName("tb_orbits")
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_orbits.setHorizontalHeaderItem(4, item)
        self.tb_orbits.horizontalHeader().setCascadingSectionResizes(False)
        self.cb_orbit_number = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_orbit_number.setGeometry(QtCore.QRect(610, 90, 121, 26))
        self.cb_orbit_number.setObjectName("cb_orbit_number")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 430, 751, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pb_convert_png = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_convert_png.setEnabled(False)
        self.pb_convert_png.setGeometry(QtCore.QRect(580, 60, 151, 30))
        self.pb_convert_png.setFlat(False)
        self.pb_convert_png.setObjectName("pb_convert_png")
        self.pbar_convert_png = QtWidgets.QProgressBar(self.groupBox_4)
        self.pbar_convert_png.setGeometry(QtCore.QRect(20, 44, 511, 23))
        self.pbar_convert_png.setMinimum(0)
        self.pbar_convert_png.setProperty("value", 0)
        self.pbar_convert_png.setObjectName("pbar_convert_png")
        self.pb_detect = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_detect.setEnabled(False)
        self.pb_detect.setGeometry(QtCore.QRect(410, 110, 151, 32))
        self.pb_detect.setObjectName("pb_detect")
        self.pbar_detect = QtWidgets.QProgressBar(self.groupBox_4)
        self.pbar_detect.setGeometry(QtCore.QRect(20, 84, 511, 23))
        self.pbar_detect.setMinimum(0)
        self.pbar_detect.setProperty("value", 0)
        self.pbar_detect.setObjectName("pbar_detect")
        self.lbl_convert = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_convert.setGeometry(QtCore.QRect(540, 43, 51, 21))
        self.lbl_convert.setObjectName("lbl_convert")
        self.lbl_detect = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_detect.setGeometry(QtCore.QRect(540, 83, 51, 21))
        self.lbl_detect.setObjectName("lbl_detect")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(20, 30, 191, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 181, 17))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStatusTip("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Near Earth Object (NEO) Finder"))
        self.groupBox.setTitle(_translate("MainWindow", "Download Data Set (.FITS):"))
        self.chb_raw.setText(_translate("MainWindow", ".fits only"))
        self.lbl_download.setText(_translate("MainWindow", "0%"))
        self.pb_download.setText(_translate("MainWindow", "Download"))
        self.pb_change_download_addr.setText(_translate("MainWindow", "..."))
        self.lbl_year.setText(_translate("MainWindow", "Year:"))
        self.lbl_doy.setText(_translate("MainWindow", "DOY:"))
        self.rb_ftp.setText(_translate("MainWindow", "FTP Address"))
        self.rb_doy.setText(_translate("MainWindow", "Day of Year"))
        self.rb_local.setText(_translate("MainWindow", "Local"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cleaning .FITS Files:"))
        self.lbl_cleaning.setText(_translate("MainWindow", "0%"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Orbit Clustering:"))
        self.pb_load_cleaned.setText(_translate("MainWindow", "Load Cleaned FITS Files"))
        self.lbl_orbit.setText(_translate("MainWindow", "0%"))
        item = self.tb_orbits.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tb_orbits.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CCD-TEMP"))
        item = self.tb_orbits.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "OBJCTRA"))
        item = self.tb_orbits.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "OBJCTDEC"))
        item = self.tb_orbits.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "OBJCTROL"))
        item = self.tb_orbits.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "OBJECT"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Find Comet/Astroid:"))
        self.pb_convert_png.setText(_translate("MainWindow", "Find Comets/NEA"))
        self.pb_detect.setText(_translate("MainWindow", "Find Comets"))
        self.lbl_convert.setText(_translate("MainWindow", "0%"))
        self.lbl_detect.setText(_translate("MainWindow", "0%"))
        self.label.setText(_translate("MainWindow", "Converting to .png file:"))
        self.label_2.setText(_translate("MainWindow", "Detecting Comets/NEA:"))
